version: '3.8' # specify docker-compose version

services:
  api:
    build: . # specify the directory of the Dockerfile
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    environment:
      - PORT=${PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

    # db:5432 is the host:port of the database.
    # This is an argument to wait-for-it.sh
    # "--" is used to separate the wait-for-it.sh arguments from the npm start arguments
    command: ['./scripts/wait-for-it.sh', 'db:5432', '--', 'npm', 'start']

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      # persist the database data by storing it in a volume
      - db-data:/var/lib/postgresql/data
      # any .sql files in this directory will be executed on database creation
      - ./data/initdb:/docker-entrypoint-initdb.d

volumes:
  db-data:
